### ISSUE TITLE
build chm2qch_gui.pro error with qt 5.12 

### ISSUE THREAD

**Issue by kunlina** [dewhisna/chm2qch#1]
/home/knd/work/GUI/chm2qch/dialog.cpp:49: error: invalid use of incomplete type ‘class QAction’
../../work/GUI/chm2qch/dialog.cpp:49:89: error: invalid use of incomplete type ‘class QAction’
   49 |     actSelectFile = new QAction(QIcon(":/res/folder.png"), tr("Select input file"), this);
      |                                                                                         ^

-------------------
add include line: #include <QAction> can fix this issue

**Comment by dewhisna** [comment]
This is fixed now in the code.  Thanks for the report.  I hadn't really been maintaining this repo since I didn't create it.  I do use it on several projects and so I copied and converted this repo from its Mercurial source on BitBucket to here on GitHub to preserve -- good thing, because it seems the original repo no longer exists, and I couldn't find where the original author has republished it anywhere.  So I guess I own it now.
